---
mariadb_service: mariadb

wordpress_db:
  name: wordpress
  user: wpuser
  password: StrongPassword1

mediawiki_db:
  name: mediawiki
  user: wikiuser
  password: StrongPassword2
 
...
