---
bind_packages:
  - bind
  - bind-utils
  
dns_search: "{{ dns_zone }}"
dns_nameserver: "{{ hostvars['servera']['ansible_host'] }}"
dns_zone: "{{ domain_name }}"
dns_service: named

dns_listen_ip: any

dns_records:
  - name: servera
    ip: "{{ hostvars['servera']['ansible_default_ipv4']['address'] }}"

  - name: serverb
    ip: "{{ hostvars['servera']['ansible_default_ipv4']['address'] }}"

  - name: wiki
    ip: "{{ hostvars['servera']['ansible_default_ipv4']['address'] }}"

  - name: www
    ip: "{{ hostvars['servera']['ansible_default_ipv4']['address'] }}"

  - name: mail
    ip: "{{ hostvars['servera']['ansible_default_ipv4']['address'] }}"

...
