---
#
# PACKAGES
#

- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ maintenance_packages }}"
    state: present

#
# HEALTHCHECK SCRIPT
#

- name: Deploy healthcheck script
  ansible.builtin.template:
    src: healthcheck.sh.j2
    dest: "{{ healthcheck_script }}"
    owner: root
    group: root
    mode: '0755'


#
# DAILY HEALTHCHECK CRON
#

- name: Configure daily healthcheck cron
  ansible.builtin.cron:
    name: "Daily NexCore healthcheck"
    minute: "{{ healthcheck_minute }}"
    hour: "{{ healthcheck_hour }}"
    job: "{{ healthcheck_script }}"

#
# WEEKLY PACKAGE CLEANUP
#

- name: Configure weekly package cleanup
  ansible.builtin.cron:
    name: "Weekly package cleanup"
    weekday: "{{ cleanup_weekday }}"
    minute: "{{ cleanup_minute }}"
    hour: "{{ cleanup_hour }}"
    job: "dnf clean all"

#
# SYSTEM UPDATE CRON
#

- name: Configure package updates
  ansible.builtin.cron:
    name: "Nightly package updates"
    minute: "{{ update_minute }}"
    hour: "{{ update_hour }}"
    job: "/usr/bin/dnf -y update"

#
# REBOOT IF REQUIRED
#

- name: Deploy reboot check script
  ansible.builtin.template:
    src: restart-check.sh.j2
    dest: /usr/local/bin/restart-check.sh
    mode: '0755'

- name: Schedule restart check 5 AM
  ansible.builtin.cron:
    name: "Reboot check"
    minute: "{{ reboot_minute }}"
    hour: "{{ reboot_hour }}"
    job: "/usr/local/bin/restart-check.sh"

#
# LOGROTATE
#

- name: Configure logrotate
  ansible.builtin.template:
    src: nexcore-health.logrotate.j2
    dest: /etc/logrotate.d/nexcore-health
    owner: root
    group: root
    mode: '0644'
...
