[all]
#servera ansible_host=192.168.56.10
#serverb ansible_host=192.168.56.11



[dns]
servera

[email]
servera

[logging]
servera

[web]
serverb

[database]
serverb

[storage]
serverb



[automount_clients]
servera
serverb

[infra:children]
dns
email
logging

[app:children]
web
database
storage
