---
- name: Create backup directory
  ansible.builtin.file:
    path: /var/backups/nexcore
    state: directory
    owner: root
    group: root
    mode: "0750"


- name: Deploy backup script
  ansible.builtin.template:
    src: db-backup.sh.j2
    dest: /usr/local/bin/nexcore-db-backup.sh
    mode: "0750"


- name: Schedule nightly backup
  ansible.builtin.cron:
    name: "NexCore DB Backup"
    minute: "0"
    hour: "1"
    job: "/usr/local/bin/nexcore-db-backup.sh"

...
